using NCMB;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using UnityEngine.Events;

namespace Communication
{
    public class LobbyManager : MonoBehaviour
    {
        public GameObject panelWalls;
        public GameObject buttonRoomCreate;
        public GameObject buttonRoomCreateExit;
        public GameObject buttonRoomEnter;
        public GameObject buttonRoomEnterExit;
        public GameObject buttonEnter;
        public GameObject buttonGame;
        public GameObject buttonMessage;
        public GameObject buttonMessageText;
        public GameObject roomCreateObject;
        public GameObject roomEnterObject;

        // â˜…è¿½åŠ 
        //public GameObject gift;
        //public Gift gift;
        
        private bool isGameStart;
        private string userName;
        private string password;

        //ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã¨çµã³ã¤ã‘ã‚‹
        public InputField inputField;
        public Text text;
        public Text textNickname;
        public Text textRoomNumber;
        public Text textInputRoomNumber;
        private string createRoomNumber; 

        private DataManager dataManager;

        // Start is called before the first frame update
        void Start()
        {
            // DBã‚¢ã‚¯ã‚»ã‚¹ç”¨ã‚¯ãƒ©ã‚¹å®£è¨€
            dataManager = new DataManager();

            // ãƒ­ãƒ¼ã‚«ãƒ«ã‹ã‚‰ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼æƒ…å ±å–å¾—
            userName = PlayerPrefs.GetString(PlayerPrefsKey.NCMB_USERNAME);
            password = PlayerPrefs.GetString(PlayerPrefsKey.NCMB_PASSWORD);

            //åˆæœŸåŒ–
            isGameStart = false;
            inputField = inputField.GetComponent<InputField> ();
            buttonRoomCreate.GetComponent<Button>().interactable = false;
            buttonRoomEnter.GetComponent<Button>().interactable = false;
            text = text.GetComponent<Text> ();
            textRoomNumber.GetComponent<Text> ();
            roomCreateObject.SetActive(false);
            roomEnterObject.SetActive(false);

            // ãƒ­ã‚°ã‚¤ãƒ³å‡¦ç†ã€ãƒã‚¤ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼å–å¾—
            StartCoroutine(InitCoroutine());
        }
        // åˆæœŸãƒ‡ãƒ¼ã‚¿å–å¾—ã‚’ã‚³ãƒ«ãƒ¼ãƒãƒ³ã«ã¦å‡¦ç†
        public IEnumerator InitCoroutine()
        {
            yield return StartCoroutine(dataManager.LoginAndSelectMyPlayerCoroutine(userName, password));
            textNickname.GetComponent<Text>().text = NCMBUser.CurrentUser[NCMBUserKey.NICKNAME] as string;

            bool changeFlag = false;
            if(dataManager.myPlayer[0][PlayerKey.PHASE] as string == PhaseKey.LOBBY_DESTROY){
                DisplayMessage("éƒ¨å±‹ã‚’çˆ†ç ´ã—ã¾ã—ãŸğŸ”¥");
                changeFlag = true;
            }else if(dataManager.myPlayer[0][PlayerKey.PHASE] as string  == PhaseKey.LOBBY_EXIT){
                DisplayMessage("éƒ¨å±‹ãŒçˆ†ç ´ã•ã‚Œã¾ã—ãŸğŸ’£");
                changeFlag = true;
            }else if(dataManager.myPlayer[0][PlayerKey.PHASE] as string  == PhaseKey.LOBBY_KICK){
                DisplayMessage("éƒ¨å±‹ã‹ã‚‰è¿½ã„å‡ºã•ã‚Œã¾ã—ãŸï¼ˆç¬‘ï¼‰");
                changeFlag = true;
            }
            if(changeFlag){
                dataManager.myPlayer[0][PlayerKey.PHASE] = PhaseKey.LOBBY;
                yield return StartCoroutine(dataManager.UpdateMyPlayerCoroutine());
            }

            // ãƒ‡ãƒ¼ã‚¿å–å¾—å®Œäº†ã™ã‚Œã°ãƒœã‚¿ãƒ³ã‚’æœ‰åŠ¹åŒ–
            buttonRoomCreate.GetComponent<Button>().interactable = true;
            buttonRoomEnter.GetComponent<Button>().interactable = true;
        }        

        private void DisplayMessage(string mes)
        {
            buttonMessage.SetActive(true);
            buttonMessageText.GetComponent<Text>().text = mes;
        }

        public void InputText(){
            //ãƒ†ã‚­ã‚¹ãƒˆã«inputFieldã®å†…å®¹ã‚’åæ˜ 
            text.text = inputField.text;
        }

        // ã€Œéƒ¨å±‹ã‚’ä½œæˆã™ã‚‹ã€ãƒœã‚¿ãƒ³ã‚’é¸ã‚“ã æ™‚ã®å‡¦ç† 
        public void PushButtonRoomCreate()
        {
            createRoomNumber = UnityEngine.Random.Range(1000,9999).ToString();
            textRoomNumber.GetComponent<Text> ().text = "éƒ¨å±‹ç•ªå·ã¯" + createRoomNumber + "ã§ã™";
            roomCreateObject.SetActive(true);
            buttonRoomCreate.GetComponent<Button>().interactable = false;
            buttonRoomEnter.GetComponent<Button>().interactable = false;
        }

        // éƒ¨å±‹ä½œæˆå¾Œã€Œé€€å®¤ã€ã‚’é¸ã‚“ã æ™‚ã®å‡¦ç† 
        public void PushButtonRoomCreateExit()
        {
            roomCreateObject.SetActive(false);
            buttonRoomCreate.GetComponent<Button>().interactable = true;
            buttonRoomEnter.GetComponent<Button>().interactable = true;
        }

        // éƒ¨å±‹ä½œæˆå¾Œã€Œå…¥å®¤ã€ã‚’é¸ã‚“ã æ™‚ã®å‡¦ç† 
        public void PushButtonRoomIn()
        {
            StartCoroutine(PushButtonRoomInCoroutine());
        }
        // éƒ¨å±‹ä½œæˆå¾Œã€Œå…¥å®¤ã€ã‚’é¸ã‚“ã æ™‚ã®å‡¦ç† (ã‚³ãƒ«ãƒ¼ãƒãƒ³)
        public IEnumerator PushButtonRoomInCoroutine()
        {
            yield return StartCoroutine(dataManager.InsertRoomDataCoroutine(createRoomNumber)) ;
            DisplayMessage("éƒ¨å±‹ã®ä½œæˆã«æˆåŠŸã—ã¾ã—ãŸ");

            yield return StartCoroutine(dataManager.InitMyPlayerCoroutine(createRoomNumber));
            DisplayMessage("éƒ¨å±‹ã«æ¥ç¶šä¸­â€¦");
            
            SceneManager.LoadScene("GameScene");
        }

        // ã€Œéƒ¨å±‹ã«å…¥ã‚‹ã€ã‚’é¸ã‚“ã æ™‚ã®å‡¦ç†
        public void PushButtonRoomEnter()
        {
            roomEnterObject.SetActive(true);
            buttonRoomCreate.GetComponent<Button>().interactable = false;
            buttonRoomEnter.GetComponent<Button>().interactable = false;
            DisplayMessage("å…¥å®¤ã™ã‚‹éƒ¨å±‹ç•ªå·ã‚’å…¥åŠ›ã—ã¦ãã ã•ã„");
        }

        // éƒ¨å±‹ç•ªå·ã‚’å…¥åŠ›ã—ã€Œå…¥å®¤ã€ã‚’é¸ã‚“ã æ™‚ã®å‡¦ç†
        public void PushButtonRoomSelect()
        {
            if(string.IsNullOrEmpty(textInputRoomNumber.text)){
                DisplayMessage("éƒ¨å±‹ç•ªå·ãŒç©ºã§ã™");
            }else{
                StartCoroutine(PushButtonRoomSelectCoroutine());
            }
        }
        // éƒ¨å±‹ã‚’é¸ã‚“ã æ™‚ã®å‡¦ç† (ã‚³ãƒ«ãƒ¼ãƒãƒ³)
        public IEnumerator PushButtonRoomSelectCoroutine()
        {
            yield return StartCoroutine(RoomEnterCoroutine());
            if(isGameStart){
                Debug.Log("GAME START");
                SceneManager.LoadScene("GameScene");  
            }
        }
        // éƒ¨å±‹ã«å…¥ã‚‹æ™‚ã®å‡¦ç†ã‚’ã•ã‚‰ã«æ¡ä»¶åˆ†å² (ã‚³ãƒ«ãƒ¼ãƒãƒ³)
        public IEnumerator RoomEnterCoroutine() {

            bool isConnecting = true;
            yield return StartCoroutine(dataManager.SelectRoomDataCoroutine(textInputRoomNumber.text));

            if(dataManager.RoomList.Count == 0){
                DisplayMessage("æ¢ã—ã¦ã„ã‚‹éƒ¨å±‹ãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“");
                isConnecting = false;
            }else if(System.Convert.ToBoolean(dataManager.RoomList[0][RoomKey.DESTROYFLAG])){
                DisplayMessage("æ¢ã—ã¦ã„ã‚‹éƒ¨å±‹ã¯çˆ†ç ´æ¸ˆã¿ã§ã™");
                isConnecting = false;            
            }else{
                DisplayMessage("éƒ¨å±‹ãŒè¦‹ã¤ã‹ã‚Šã¾ã—ãŸ");
                            
                if(textInputRoomNumber.text == dataManager.myPlayer[0][PlayerKey.ENTERROOM] as string){
                    if(dataManager.myPlayer[0][PlayerKey.PHASE] as string == PhaseKey.GAME){
                        SceneManager.LoadScene("GameScene");
                    }else if(dataManager.myPlayer[0][PlayerKey.PHASE] as string == PhaseKey.PLAY){
                        SceneManager.LoadScene("PlayScene");
                    }
                }else{
                    // åˆæœŸåŒ–ã—ã¦ GAMEã‚·ãƒ¼ãƒ³ã¸
                    yield return StartCoroutine(dataManager.InitMyPlayerCoroutine(textInputRoomNumber.text));
                    DisplayMessage("éƒ¨å±‹ã«æ¥ç¶šä¸­â€¦");

                    isGameStart = true;
                    isConnecting = false;
                }
            }

            while (isConnecting) { yield return null; }           
        }

        // éƒ¨å±‹é¸æŠæ™‚ã«ã€Œæˆ»ã‚‹ã€ãƒœã‚¿ãƒ³ã‚’æŠ¼ã—ãŸæ™‚ã®å‡¦ç†
        public void PushButtonRoomEnterExit()
        {
            roomEnterObject.SetActive(false);
            buttonRoomCreate.GetComponent<Button>().interactable = true;
            buttonRoomEnter.GetComponent<Button>().interactable = true;
        }

        // ã€Œæˆç¸¾ã‚’è¦‹ã‚‹ã€ã‚’é¸ã‚“ã æ™‚ã®å‡¦ç†
        public void PushButtonGrades()
        {
            SceneManager.LoadScene("GradesScene");  
        }

        // ãƒ­ãƒ¼ã‚«ãƒ«ã«ä¿å­˜ã—ãŸãƒ¦ãƒ¼ã‚¶æƒ…å ±ã‚’å–å¾—
        public string LocalSavedUserName
        {
            get
            {
                return PlayerPrefs.HasKey(PlayerPrefsKey.NCMB_USERNAME) ?
                    PlayerPrefs.GetString(PlayerPrefsKey.NCMB_USERNAME) : string.Empty;
            }
        }

        // Update is called once per frame
        void Update()
        {
            
        }
    }
}
